# English file
# Login
mailLabel = Mail address
mailPrompt = Your mail address
passwordLabel = Password
passwordPrompt = Your password
loginButton = Login
registerButton = Create a new account

# Main menu
mainMenuLabel = Main menu
runSessionButton = Launch a session
exerciseButton = Show my exercises
programButton = Show my programs
editProfile = Edit my profile
signOut = Sign out
settingsLabel = Settings
backButton = Back
welcome = Welcome

# Settings
visualizationLabel = Visualization mode
visualizationButton = Light/Dark mode
languageLabel = App's language
measurementUnitsLabel = Measurement units

# Session
sessionLabel = Session list
selectProgramLabel = Select a program
typeLabel = Type
selectedProgramLabel = Selected program
selected = Selected
startButton = Start

# Run session
exerciseNameLabel = Exercise's name
pauseButton = Pause
nextButton = Next
previousButton = Previous
endButton = End

# Exercise/Program list
exerciseList = Exercises list
programList = Programs list
addButton = Add
editButton = Edit
deleteButton = Delete
filterByTypeLabel = Filter by type

# Add exercise
exerciseAdditionLabel = Create an exercise
nameLabel = Name
exerciseNamePrompt = Exercise's name
descriptionLabel = Description
exerciseDescriptionPrompt = Exercise's description
difficultyLabel = Difficulty
imageLabel = Image
imageButton = Choose an image
muscleLabel = Muscle
durationLabel = Duration (min)
caloriesLabel = Calories
caloriesPrompt = Choose your calorie's option
addExercise = Add exercise

#Modification exercise/program
modifyProgramTitle= Edit program
modifyProgramButton = Edit
modifyExerciseTitle= Edit Exercise
modifyExerciseButton = Edit

# Program list
programTitle = Create a program
programNamePrompt = Program's name
programDescriptionPrompt = Program's description
filterSettingsLabel = Filter settings
exerciseTypeRadio = Exercise type
exerciseFilterPrompt = Filters...
exercisesListLabel = Exercises
exerciseListPrompt = Exercises...
pauseTypeLabel = Break type
coolPauseRadio = Cool 1 min
normalPauseRadio = Normal 30s
intensePauseRadio = Intense 15s
repsLabel = Reps
repsPrompt = Number of repetitions
addProgram = Add program

# My profile
myProfile = My profile
firstNameLabel = First name
firstNamePrompt = Your first name
lastNameLabel = Last name
lastNamePrompt = Your last name
heightLabel = Height
heightPrompt = Your height
weightLabel = Weight
weightPrompt = Your weight
pullUpLabel = Maximum pull ups
pullUpPrompt = Max of possible pull ups
absLabel = Maximum abs
absPrompt = Max of possible abs
pushUpLabel = Maximum push ups
pushUpPrompt = Max of possible push ups
kmLabel = Maximum of kilometer
kmPrompt = Max of possible km
repeatPassLabel = Confirm with your password
repeatPassPrompt = Repeat your password
editProfilButton = Edit profile
backtoMenu = Back to the menu

#popup Ex
ExerciseRemove = The exercise has been successfully removed.
ExerciseNotRemove = The exercise could not be removed.
WrongArgument = Error: incorrect argument.
impossibleGettingExercises = The exercises could not be retrieved. Please try again.
MuscleNotRecognize = No muscle recognized.
addingExerciseProblem = A problem occurred while adding an exercise.
badArgument = Unable to complete the task, one of the received arguments is incorrect.
ExerciseAlreadyExist = An exercise with the same name already exists.
UploadImageError = An error occurred, the image could not be uploaded.
IncorrectForm = The form was not filled out correctly. Please ensure all fields are completed.
ExerciseInsert = The new exercise has been added to your list.
MuscleProblem = Error loading the muscle(s).
ExerciseMuscleProblem = Error modifying the exercise.
ExerciseModified = The exercise has been modified!
ExercisesError = Error loading the exercises. Please reload the page
#popup login
FormPopup = Please fill in all fields.
AccountNotExist = The account does not exist. Please consider creating an account.
loginError = Error verifying the connection.
MailAddressAlreadyTaken = This email address is already taken.
ModifyProfileFormError = Incorrect data/empty fields. Please ensure your passwords match.
AccountModified = Your data has been successfully modified!

#popup registration
registrationOk = Registration successful!
registrationError = An error occurred. Please try registering again.
contactAdmin = An error occurred, please contact the administrators.

#popup programme
ProgramAlreadyExist = A program with the same name already exists.
ProgramAdded = The program has been added.
ProgramModified = The program has been modified.

programFormError = An error occurred.
programGetError = The programs could not be retrieved.
programRemoved = The program has been successfully removed.
programRemovedError = The program could not be removed.

#popup session
sessionNotcharged = The program was not loaded!
sessionNoExercise = The exercise list for the selected program is empty!
getExerciseError = Unable to retrieve the exercise list. Please try again.

#popup settings
settingsError= An error occurred when updating preferences!