# French file
# Login
mailLabel = Adresse mail
mailPrompt = Votre adresse mail
passwordLabel = Mot de passe
passwordPrompt = Votre mot de passe
loginButton = Se connecter
registerButton = Créer un nouveau compte

# Main menu
mainMenuLabel = Menu principal
runSessionButton = Lancer une séance
exerciseButton = Afficher mes exercices
programButton = Afficher les programmes
editProfile = Modifier mon profil
signOut = Déconnexion
settingsLabel = Paramètres
backButton = Retour
welcome = Bienvenue

# Settings
visualizationLabel = Paramètres de visualisation
visualizationButton = Mode jour/nuit
languageLabel = Langue de l'application
measurementUnitsLabel = Unités de mesure

# Session
sessionLabel = Liste de séances
selectProgramLabel = Choisir un programme
typeLabel = Type
selectedProgramLabel = Programme sélectionné
selected = Sélection
startButton = Lancer

# Run session
exerciseNameLabel = Nom exercice
pauseButton = Pause
nextButton = Suivant
previousButton = Précédent
endButton = Terminé

# exercice/programme list
exerciseList = Liste des exercices
programList = Liste des programmes
addButton = Ajouter
editButton = Modifier
deleteButton = Supprimer
filterByTypeLabel = Filtrer par type

# Add exercice
exerciseAdditionLabel = Créer un exercice
nameLabel = Nom
exerciseNamePrompt = Nom de l'exercice
descriptionLabel = Description
exerciseDescriptionPrompt = Description de l'exercice
difficultyLabel = Difficulté
imageLabel = Image
imageButton = Choisir une image
muscleLabel = Muscle
durationLabel = Durée (min)
caloriesLabel = Calories
caloriesPrompt = Choisissez l'option des calories
addExercise = Ajouter exercice

#Modification exercise/program
modifyProgramTitle = Modification Programme
modifyProgramButton = Modifier
modifyExerciseTitle = Modification d'un exercice
modifyExerciseButton = Modifier

# programme list
programTitle = Créer un programme
programNamePrompt = Nom du programme
programDescriptionPrompt = Description du programme
filterSettingsLabel = Paramètres de filtrage
exerciseTypeRadio = Type d'exercice
exerciseFilterPrompt = Filtres...
exercisesListLabel = Exercices
exerciseListPrompt = Exercices...
pauseTypeLabel = Type de pause
coolPauseRadio = Calme 1 min
normalPauseRadio = Normale 30s
intensePauseRadio = Intense 15s
repsLabel = Répétitions
repsPrompt = Nombre de répétitions
addProgram = Ajouter programme

# My profile
myProfile = Mon profil
firstNameLabel = Prénom
firstNamePrompt = Votre prénom
lastNameLabel = Nom
lastNamePrompt = Votre nom
heightLabel = Taille
heightPrompt = Votre taille
weightLabel = Poids
weightPrompt = Votre poids
pullUpLabel = Maximum tractions
pullUpPrompt = Max de tractions possible
absLabel = Maximum abdominaux
absPrompt = Max abdominaux possible
pushUpLabel = Maximum pompes
pushUpPrompt = Max de pompes possible
kmLabel = Maximum de kilomètres
kmPrompt = Max de km possible
repeatPassLabel = Confirmer votre mot de passe
repeatPassPrompt = Répétez votre mot de passe
editProfilButton = Modifier profil
backtoMenu = Retour à l'accueil 

#popup Ex
ExerciseRemove = L'exercice a été correctement enlevé.
ExerciseNotRemove = L'exercice n'a pas pu être enlevé.
WrongArgument = Erreur : argument incorrect.
impossibleGettingExercises = Les exercices n'ont pas pu être récupérés. Veuillez réessayer.
MuscleNotRecognize = Aucun muscle reconnu.
addingExerciseProblem = Un problème est survenu lors de l'ajout d'un exercice.
badArgument = Impossible d'accomplir la tâche, un des arguments reçus est incorrect.
ExerciseAlreadyExist = Un exercice du même nom existe déjà.
UploadImageError = Une erreur est survenue, l'image n'a pas pu être téléchargée.
IncorrectForm = Le formulaire n'a pas été rempli correctement. Veuillez remplir tous les champs.
ExerciseInsert = Le nouvel exercice a été ajouté à votre liste.
MuscleProblem = Erreur au chargement du/des muscle(s).
ExerciseMuscleProblem = Erreur lors de la modification de l'exercice.
ExerciseModified = L'exercice a été modifié !
ExercisesError = Impossible de récupérer la liste d'exercices. Veuillez réessayer.
#popup login
FormPopup = Veuillez remplir tous les champs.
AccountNotExist = Le compte n'existe pas. Pensez à créer un compte.
loginError = Erreur lors de la vérification de la connexion.
MailAddressAlreadyTaken = Cette adresse mail est déjà prise.
ModifyProfileFormError = Données incorrectes/champs vides. Veuillez vérifier que vos mots de passe correspondent.
AccountModified = Vos données ont bien été modifiées !

#popup registration
registrationOk = Inscription réussie !
registrationError = Une erreur s'est produite. Veuillez réessayer de vous inscrire.
contactAdmin = Une erreur est survenue, veuillez contacter les administrateurs.

#popup programme
ProgramAlreadyExist = Un programme du même nom existe déjà.
ProgramAdded = Le programme a été ajouté.
ProgramModified = Le programme a été modifié.
programmFormError = Une erreur s'est produite.
programGetError = Les programmes n'ont pas pu être récupérés.
programRemoved = Le programme a été correctement enlevé.
programRemovedError = Le programme n'a pas pu être enlevé.

#popup session
sessionNotcharged = Le programme n'a pas été chargé !
sessionNoExercise = La liste d'exercices du programme sélectionné est vide !
getExerciseError = Impossible de récupérer la liste d'exercices. Veuillez réessayer.

#popup settings
settingsError= Une erreur c'est produite à la mise à jour des préférences !